# Generated by Django 5.2.17 on 2026-08-28 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('cash', 'Наличные'), ('consignment', 'Под реализацию'), ('debt', 'В долг')], default='cash', max_length=16, verbose_name='Тип оплаты')),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Сумма продажи')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('is_processed', models.BooleanField(default=False, editable=False, verbose_name='Проведена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата продажи')),
                ('client', models.ForeignKey(blank=True, help_text='Для наличной продажи можно не указывать.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='clients.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=3, help_text='Сколько выбранных фасовок (или базовых единиц).', max_digits=12, verbose_name='Количество')),
                ('base_quantity', models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=12, verbose_name='В базовых ед.')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='За базовую единицу. Пусто → возьмём отпускную цену товара.', max_digits=12, verbose_name='Цена за ед.')),
                ('packaging', models.ForeignKey(blank=True, help_text='Пусто = количество в базовых единицах.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.packagingunit', verbose_name='Фасовка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='catalog.product', verbose_name='Товар')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale', verbose_name='Продажа')),
            ],
            options={
                'verbose_name': 'Позиция продажи',
                'verbose_name_plural': 'Позиции продажи',
            },
        ),
    ]
