# Generated by Django 5.2.17 on 2026-09-07 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('cash', 'Наличные'), ('debt', 'Реализация')], default='cash', max_length=16, verbose_name='Тип оплаты')),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='Сумма продажи')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('is_processed', models.BooleanField(default=False, editable=False, verbose_name='Проведена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата продажи')),
                ('client', models.ForeignKey(blank=True, help_text='Для наличной продажи можно не указывать.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='clients.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packs', models.PositiveIntegerField(verbose_name='Количество, фасовок')),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Цена за базовую единицу (штуку). У разных клиентов разная.', max_digits=12, verbose_name='Цена за штуку')),
                ('cogs', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='Себестоимость (FIFO)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='catalog.product', verbose_name='Товар')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale', verbose_name='Продажа')),
            ],
            options={
                'verbose_name': 'Позиция продажи',
                'verbose_name_plural': 'Позиции продажи',
            },
        ),
    ]
