# Generated by Django 5.2.17 on 2026-08-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Наличные'), ('debt', 'Реализация')], default='cash', max_length=16, verbose_name='Тип оплаты'),
        ),
    ]
