# Generated by Django 5.2.17 on 2026-09-07 10:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('debts', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Приход'), ('out', 'Расход')], max_length=8, verbose_name='Тип')),
                ('category', models.CharField(choices=[('sale', 'Продажа (наличные)'), ('debt_payment', 'Оплата долга (реализация)'), ('investment', 'Инвестиции'), ('other_in', 'Прочий приход'), ('purchase', 'Закупка товара'), ('delivery', 'Доставка'), ('rent', 'Аренда'), ('salary', 'Зарплата'), ('personal', 'Личные расходы (Атай)'), ('other_out', 'Прочий расход')], max_length=20, verbose_name='Категория')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('debt_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_flows', to='debts.debtpayment', verbose_name='Оплата долга-источник')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_flows', to='sales.sale', verbose_name='Продажа-источник')),
            ],
            options={
                'verbose_name': 'Движение денег',
                'verbose_name_plural': 'Касса / движения денег',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['direction', 'date'], name='finance_cas_directi_9bda05_idx')],
            },
        ),
    ]
