# Generated by Django 5.2.17 on 2026-09-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='subcategory',
            field=models.CharField(blank=True, max_length=64, verbose_name='Статья'),
        ),
    ]
