# Generated by Django 5.2.17 on 2026-10-05 16:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_cashflow_subcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Obligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('code', models.SlugField(help_text='Служебный идентификатор для кнопок бота. Менять не нужно.', max_length=32, unique=True, verbose_name='Код')),
                ('currency', models.CharField(choices=[('KGS', 'сом'), ('USD', 'доллар')], default='KGS', max_length=3, verbose_name='Валюта')),
                ('rate', models.DecimalField(decimal_places=2, default=1, help_text='Для долга в долларах. Заказчик просил фиксированный курс.', max_digits=10, verbose_name='Курс к сому')),
                ('opening_amount', models.DecimalField(decimal_places=2, help_text='В валюте обязательства. От него вычитаются платежи.', max_digits=14, verbose_name='Начальный остаток')),
                ('default_payment', models.DecimalField(blank=True, decimal_places=2, help_text='Если задан, бот гасит эту сумму одним нажатием, без вопросов.', max_digits=14, null=True, verbose_name='Платёж по умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Наш долг / кредит',
                'verbose_name_plural': 'Наши долги и кредиты',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='category',
            field=models.CharField(choices=[('sale', 'Продажа (наличные)'), ('debt_payment', 'Оплата долга (реализация)'), ('investment', 'Инвестиции'), ('other_in', 'Прочий приход'), ('purchase', 'Закупка товара'), ('delivery', 'Доставка'), ('rent', 'Аренда'), ('salary', 'Зарплата'), ('personal', 'Личные расходы (Атай)'), ('loan_payment', 'Погашение кредита / долга'), ('other_out', 'Прочий расход')], max_length=20, verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='ObligationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reversed', models.BooleanField(default=False, editable=False, verbose_name='Сторнирован')),
                ('reversed_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата сторно')),
                ('reversal_reason', models.CharField(blank=True, editable=False, max_length=255, verbose_name='Причина сторно')),
                ('amount', models.DecimalField(decimal_places=2, help_text='В валюте обязательства.', max_digits=14, verbose_name='Сумма платежа')),
                ('rate', models.DecimalField(decimal_places=2, default=1, help_text='Снимок: потом курс поменяется, а платёж должен остаться как был.', max_digits=10, verbose_name='Курс на момент платежа')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.obligation', verbose_name='Долг / кредит')),
                ('reversed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто сторнировал')),
            ],
            options={
                'verbose_name': 'Платёж по долгу',
                'verbose_name_plural': 'Платежи по нашим долгам',
                'ordering': ['-created_at'],
            },
        ),
    ]
