# Generated by Django 5.2.17 on 2026-10-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_credit_balances'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obligationpayment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Движение по долгу', 'verbose_name_plural': 'Движения по нашим долгам'},
        ),
        migrations.AddField(
            model_name='obligation',
            name='allow_charge',
            field=models.BooleanField(default=False, help_text='У банковского кредита сумма фиксирована, а личный заём можно доливать. Если включено — бот покажет кнопку «Занять ещё».', verbose_name='Можно занимать ещё'),
        ),
        migrations.AddField(
            model_name='obligationpayment',
            name='kind',
            field=models.CharField(choices=[('payment', 'Погашение'), ('charge', 'Новый заём')], default='payment', max_length=8, verbose_name='Тип'),
        ),
    ]
