# Generated by Django 5.2.17 on 2026-10-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_allow_charge_ashimzhan'),
    ]

    operations = [
        migrations.AddField(
            model_name='obligation',
            name='payment_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Число месяца, когда вносится платёж (1–28). Если задано, бот напомнит заранее. Пусто — напоминаний не будет.', null=True, verbose_name='День платежа'),
        ),
        migrations.AddField(
            model_name='obligation',
            name='remind_days_before',
            field=models.PositiveSmallIntegerField(default=2, help_text='За сколько дней до платежа слать напоминание.', verbose_name='Напомнить за, дней'),
        ),
    ]
