# Generated by Django 5.2.17 on 2026-10-09 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_obligation_reminders'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('category', models.CharField(choices=[('sale', 'Продажа (наличные)'), ('debt_payment', 'Оплата долга (реализация)'), ('investment', 'Инвестиции'), ('other_in', 'Прочий приход'), ('purchase', 'Закупка товара'), ('delivery', 'Доставка'), ('rent', 'Аренда'), ('salary', 'Зарплата'), ('personal', 'Личные расходы (Атай)'), ('loan_payment', 'Погашение кредита / долга'), ('other_out', 'Прочий расход')], default='other_out', help_text='По ней считается прибыль. Зарплата — «Зарплата», бухуслуги и страховка — «Прочий расход».', max_length=20, verbose_name='Категория')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма в месяц, сом')),
                ('day', models.PositiveSmallIntegerField(blank=True, help_text='Число месяца, когда расход записывается. Пусто — последний день месяца.', null=True, verbose_name='День проведения')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, help_text='Выключите, вместо того чтобы удалять: проведённые расходы за прошлые месяцы останутся на месте.', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Постоянный расход',
                'verbose_name_plural': 'Постоянные расходы',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='cashflow',
            name='recurring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postings', to='finance.recurringexpense', verbose_name='Постоянный расход-источник'),
        ),
    ]
