# Generated by Django 5.2.17 on 2026-09-07 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Себестоимость за шт')),
                ('packs_received', models.PositiveIntegerField(verbose_name='Приход, фасовок')),
                ('packs_remaining', models.PositiveIntegerField(default=0, editable=False, verbose_name='Остаток, фасовок')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата прихода')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Партия (приход)',
                'verbose_name_plural': 'Партии / приходы',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packs', models.PositiveIntegerField(verbose_name='Списано, фасовок')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Себестоимость за шт (снимок)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='warehouse.batch', verbose_name='Партия')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='sales.saleitem', verbose_name='Позиция продажи')),
            ],
            options={
                'verbose_name': 'Списание из партии',
                'verbose_name_plural': 'Списания из партий',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['product', 'created_at'], name='warehouse_b_product_9a9a37_idx'),
        ),
    ]
