# Generated by Django 5.2.17 on 2026-08-26 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('receipt', 'Приход'), ('sale', 'Продажа'), ('adjustment', 'Корректировка')], max_length=16, verbose_name='Тип движения')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Со знаком: приход +, продажа −. Остаток = сумма всех движений.', max_digits=12, verbose_name='Количество (± базовых ед.)')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Складское движение',
                'verbose_name_plural': 'Складские движения',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'created_at'], name='warehouse_s_product_eae43e_idx')],
            },
        ),
    ]
