# Generated by Django 5.2.17 on 2026-08-28 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=3, help_text='Сколько выбранных фасовок (или базовых единиц, если фасовка не выбрана).', max_digits=12, verbose_name='Количество')),
                ('base_quantity', models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=12, verbose_name='Итого в базовых единицах')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('movement', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt', to='warehouse.stockmovement', verbose_name='Складское движение')),
                ('packaging', models.ForeignKey(blank=True, help_text='Пусто = количество указано в базовых единицах товара.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.packagingunit', verbose_name='Фасовка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Приход партии',
                'verbose_name_plural': 'Приходы партий',
                'ordering': ['-created_at'],
            },
        ),
    ]
