# Generated by Django 5.2.17 on 2026-09-16 10:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='По умолчанию — сейчас. Можно указать прошедшую дату.', verbose_name='Дата прихода'),
        ),
        migrations.AlterField(
            model_name='batchconsumption',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
