# Generated by Django 5.2.17 on 2026-09-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receives_notifications',
            field=models.BooleanField(default=False, help_text='Слать этому сотруднику уведомления бота (напр. низкий остаток). Нужен заполненный Telegram ID.', verbose_name='Получает уведомления'),
        ),
    ]
