# Generated by Django 5.2.17 on 2026-08-28 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsignmentStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_given', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Передано (базовых ед.)')),
                ('quantity_settled', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Погашено (базовых ед.)')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена за ед.')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consignments', to='clients.client', verbose_name='Клиент')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consignments', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар на реализации',
                'verbose_name_plural': 'Товары на реализации',
                'ordering': ['-created_at'],
            },
        ),
    ]
