# Generated by Django 5.2.17 on 2026-08-30 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsignmentStock',
        ),
    ]
