# Generated by Django 5.2.17 on 2026-09-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Неактивные не показываются в боте при продаже и оплате долга. Историю и долги не трогает — просто убирает из списков выбора.', verbose_name='Активный'),
        ),
    ]
