# Generated by Django 5.2.17 on 2026-08-26 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('base_unit', models.CharField(default='шт', help_text='Наименьшая единица учёта (шт, кг, л). В ней считается остаток.', max_length=32, verbose_name='Базовая единица')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Себестоимость (за ед.)')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Отпускная цена (за ед.)')),
                ('low_stock_threshold', models.DecimalField(decimal_places=3, default=0, help_text='Если остаток опустится ниже — товар попадёт в список на пополнение.', max_digits=12, verbose_name='Порог низкого остатка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PackagingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Напр.: блок, коробка, упаковка', max_length=64, verbose_name='Название фасовки')),
                ('quantity_in_base', models.DecimalField(decimal_places=3, help_text='Сколько базовых единиц в одной такой упаковке. Напр.: коробка = 96.', max_digits=12, verbose_name='Базовых единиц в фасовке')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packagings', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фасовка',
                'verbose_name_plural': 'Фасовки',
                'unique_together': {('product', 'name')},
            },
        ),
    ]
