# Generated by Django 5.2.17 on 2026-09-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('base_unit', models.CharField(default='шт', help_text='Единица внутри фасовки (шт, кг). Цена/себестоимость — за неё.', max_length=32, verbose_name='Базовая единица')),
                ('pack_name', models.CharField(default='коробка', help_text='Как называется фасовка: коробка, блок, мешок…', max_length=64, verbose_name='Фасовка')),
                ('units_per_pack', models.PositiveIntegerField(default=1, help_text='Сколько базовых единиц в одной фасовке (напр. коробка = 96).', verbose_name='Штук в фасовке')),
                ('low_stock_threshold', models.PositiveIntegerField(default=0, help_text='Если остаток в фасовках ниже — товар попадёт на пополнение.', verbose_name='Порог низкого остатка (фасовок)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
            },
        ),
    ]
