# Generated by Django 5.2.17 on 2026-09-16 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0002_alter_debt_created_at_alter_debtpayment_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='is_reversed',
            field=models.BooleanField(default=False, editable=False, verbose_name='Сторнирован'),
        ),
        migrations.AddField(
            model_name='debt',
            name='reversal_reason',
            field=models.CharField(blank=True, editable=False, max_length=255, verbose_name='Причина сторно'),
        ),
        migrations.AddField(
            model_name='debt',
            name='reversed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата сторно'),
        ),
        migrations.AddField(
            model_name='debt',
            name='reversed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто сторнировал'),
        ),
        migrations.AddField(
            model_name='debtpayment',
            name='is_reversed',
            field=models.BooleanField(default=False, editable=False, verbose_name='Сторнирован'),
        ),
        migrations.AddField(
            model_name='debtpayment',
            name='reversal_reason',
            field=models.CharField(blank=True, editable=False, max_length=255, verbose_name='Причина сторно'),
        ),
        migrations.AddField(
            model_name='debtpayment',
            name='reversed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата сторно'),
        ),
        migrations.AddField(
            model_name='debtpayment',
            name='reversed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто сторнировал'),
        ),
    ]
