# Generated by Django 5.2.17 on 2026-08-30 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debt',
            options={'ordering': ['-created_at'], 'verbose_name': 'Долг по реализации', 'verbose_name_plural': 'Реализация (долги клиентов)'},
        ),
    ]
